
import logging
import os
import httpx
from typing import Optional
from mcp.server import Server
from mcp.types import Tool, TextContent
from pydantic import Field

logger = logging.getLogger("email-mcp")

# Initialize MCP server
email_server = Server("email-server")


def create_itinerary_html(destination: str, itinerary_content: str) -> str:
    """
    Create a beautifully formatted HTML email for the itinerary.

    Args:
        destination: Trip destination
        itinerary_content: Markdown-formatted itinerary content

    Returns:
        HTML string for email body
    """
    # Convert basic markdown to HTML
    html_content = itinerary_content

    # Convert headers
    html_content = html_content.replace("# ", "<h2>").replace("\n", "</h2>\n", html_content.count("# "))

    # Convert bullet points
    lines = html_content.split("\n")
    formatted_lines = []
    in_list = False

    for line in lines:
        if line.strip().startswith("* ") or line.strip().startswith("- "):
            if not in_list:
                formatted_lines.append("<ul style='margin-left: 20px;'>")
                in_list = True
            formatted_lines.append(f"<li style='margin-bottom: 8px;'>{line.strip()[2:]}</li>")
        else:
            if in_list:
                formatted_lines.append("</ul>")
                in_list = False
            if line.strip().startswith("<h2>"):
                formatted_lines.append(f"<div style='margin-top: 24px; margin-bottom: 12px;'>{line}</div>")
            elif line.strip():
                formatted_lines.append(f"<p style='margin: 10px 0;'>{line}</p>")
            else:
                formatted_lines.append("<br>")

    if in_list:
        formatted_lines.append("</ul>")

    formatted_content = "\n".join(formatted_lines)

    # Wrap in beautiful HTML template
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Travel Itinerary - {destination}</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5;">
    <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 30px; text-align: center;">
            <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 600;">🎙️ Voice Travel Agent</h1>
            <p style="margin: 10px 0 0 0; color: #e0e7ff; font-size: 16px;">Your Personalized Travel Itinerary</p>
        </div>

        <!-- Destination Banner -->
        <div style="background-color: #4f46e5; padding: 20px 30px; text-align: center;">
            <h2 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 500;">📍 {destination}</h2>
        </div>

        <!-- Content -->
        <div style="padding: 30px;">
            {formatted_content}
        </div>

        <!-- Footer -->
        <div style="background-color: #f9fafb; padding: 30px; text-align: center; border-top: 1px solid #e5e7eb;">
            <p style="margin: 0 0 10px 0; color: #6b7280; font-size: 14px;">
                Have a wonderful trip! ✈️
            </p>
            <p style="margin: 0; color: #9ca3af; font-size: 12px;">
                Generated by Voice Travel Agent • Powered by ElevenLabs, Groq, and LangGraph
            </p>
        </div>
    </div>
</body>
</html>
"""
    return html


@email_server.list_tools()
async def list_tools() -> list[Tool]:
    """List available email tools."""
    return [
        Tool(
            name="send_itinerary_email",
            description="Send a travel itinerary to an email address via Resend. Use this when the user wants to email their itinerary.",
            inputSchema={
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "description": "Recipient email address"
                    },
                    "destination": {
                        "type": "string",
                        "description": "Trip destination (e.g., 'Paris, France')"
                    },
                    "itinerary_content": {
                        "type": "string",
                        "description": "The complete itinerary content in markdown format"
                    }
                },
                "required": ["email", "destination", "itinerary_content"]
            }
        )
    ]


@email_server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    """Handle tool calls for email operations."""

    if name == "send_itinerary_email":
        email = arguments["email"]
        destination = arguments["destination"]
        itinerary_content = arguments["itinerary_content"]

        logger.info(f"Sending itinerary email to {email} for {destination}")

        try:
            # Get Resend API key from environment
            api_key = os.environ.get("RESEND_API_KEY")
            if not api_key:
                logger.error("RESEND_API_KEY not found in environment")
                return [TextContent(
                    type="text",
                    text="Error: Email service not configured. Please set RESEND_API_KEY."
                )]

            # Get sender settings
            sender_email = os.environ.get("EMAIL_SENDER", "onboarding@resend.dev")
            sender_name = os.environ.get("EMAIL_SENDER_NAME", "Voice Travel Agent")

            # Create HTML email
            html_body = create_itinerary_html(destination, itinerary_content)

            # Send email via Resend API
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    "https://api.resend.com/emails",
                    headers={
                        "Authorization": f"Bearer {api_key}",
                        "Content-Type": "application/json"
                    },
                    json={
                        "from": f"{sender_name} <{sender_email}>",
                        "to": [email],
                        "subject": f"Your Travel Itinerary - {destination}",
                        "html": html_body
                    },
                    timeout=30.0
                )

            if response.status_code == 200:
                result = response.json()
                logger.info(f"Email sent successfully. ID: {result.get('id')}")
                return [TextContent(
                    type="text",
                    text=f"Itinerary sent successfully to {email}!"
                )]
            else:
                error_data = response.json()
                logger.error(f"Failed to send email: {response.status_code} - {error_data}")
                return [TextContent(
                    type="text",
                    text=f"Failed to send email: {error_data.get('message', 'Unknown error')}"
                )]

        except Exception as e:
            logger.error(f"Error sending email: {e}", exc_info=True)
            return [TextContent(
                type="text",
                text=f"Error sending email: {str(e)}"
            )]

    return [TextContent(type="text", text=f"Unknown tool: {name}")]
